const locale = {
    EN: {
        descriptionTitle: "Description",
        howManyLeftTitle: "How many left?",
        howManyLeftContent: "You need to score at least % points more to get the final geocache coordinates!\nKeep loking! :-)",
        finalTitle: "Final geocache",
        finalSuccessMessage: "Great! You have found the required number of places. Now you can go and grab the final geocache.",
        finalContent: "The geocache is hidden here:\n%\n",
        hintTitle: "Hint",
        spoiler: "Spoiler",
        welcome: "Welcome %!",
        worthPoints: "This zone was worth % points.",
        completionCodeTitle: "Completion Code",
        completionCodeContent: "Your wherigo completion code is:",
        questionTitle: "Question",
        correctAnswerMessage: "Yay! That is a correct answer!",
        invalidAnswerMessage: "Nope. This is not a correct answer.",
        answerNoValidation: "Your response has been recorded in the cartridge. It did not check its correctness, because it will use it to calculate the final coordinates.\nYou can change the answer by clicking the \"%\" task in the player. If the checker in the listing says the coordinates are invalid after completing the game, you should use that option.",
        yourPreviousAnswerIs: "Your previous answer is: %",
        coordinatesCalculationWarning: '\nWARNING: The final coordinates has been calculated based on some answers you provide in the game. Make sure to validate them with the checker that should be provided in the listing. If they are not correct, check the answers you provided for the tasks marked with an asterisk \"*\". You can re-enter the answers for them by clicking on the tasks in the player. After making any changes, check the recalculated coordinates here.',
    },
    PL: {
        descriptionTitle: "Opis",
        howManyLeftTitle: "Ile zostało?",
        howManyLeftContent: "Musisz zebrać jeszcze co najmniej % punktów, by zdobyć współrzędne finału!\nSzukaj dalej! :-)",
        finalTitle: "Finał",
        finalSuccessMessage: "Świetnie! Udało ci się odnaleźć wymaganą liczbę miejsc. Możesz teraz odnaleźć skrytkę finałową.",
        finalContent: "Geocache jest ukryty tutaj:\n%\n",
        hintTitle: "Hint",
        spoiler: "Spoiler",
        welcome: "Witaj %!",
        worthPoints: "Ta strefa była warta % punktów.",
        completionCodeTitle: "Kod Wherigo",
        completionCodeContent: "Kod weryfikacyjny Wherigo:",
        questionTitle: "Pytanie",
        correctAnswerMessage: "Tak! To jest poprawna odpowiedź!",
        invalidAnswerMessage: "Niestety to nie jest poprawna odpowiedź.",
        answerNoValidation: "Twoja odpowiedź została zapisana w scenariuszu. Scenariusz nie sprawdził jej poprawności, ponieważ zostanie ona użyta do obliczenia współrzędnych finału.\nMożesz zmienić wprowadzoną odpowiedź za pomocą kliknięcia w zadanie \"%\" w scenariuszu. Jeśli po przejściu całego scenariusza checker z listingu nie potwierdzi poprawności współrzędnych obliczonych przez kartridż, należy skorzystać z tej opcji.",
        yourPreviousAnswerIs: "Twoja poprzednia odpowiedź to: %",
        coordinatesCalculationWarning: '\nUWAGA: Współrzędne skrytki finałowej zostały obliczone na podstawie udzielonych przez ciebie odpowiedzi w trakcie gry. Sprawdź je za pomocą checkera, który powinien być udostępniony w listingu skrytki. Jeśli okaże się, że nie są poprawne, sprawdź swoje odpowiedzi udzielone do zadań oznaczonych gwiazdką \"*\". Możesz poprawić swoje odpowiedzi klikając w zadania w twoim playerze. Po dokonaniu zmian, sprawdź ponownie współrzędne finału w tym miejscu.',
    },
};
