const locale = {
    EN: {
        howManyLeftTitle: "How many left?",
        howManyLeftContent: "You need to score at least % points more to get the final geocache coordinates!\nKeep loking! :-)",
        finalTitle: "Final geocache",
        finalSuccessMessage: "Great! You have found the required number of places. Now you can go and grab the final geocache.",
        finalContent: "The geocache is hidden here:\n%\n",
        hint: "Hint",
        spoiler: "Spoiler",
        welcome: "Welcome %!",
        worthPoints: "This zone was worth % points.",
        completionCodeTitle: "Completion Code",
        completionCodeContent: "Your wherigo completion code is:",
    },
    PL: {
        howManyLeftTitle: "Ile zostalo?",
        howManyLeftContent: "Musisz zebrac jeszcze co najmniej % punktow by zdobyc wspolrzedne finalu!\nSzukaj dalej! :-)",
        finalTitle: "Final",
        finalSuccessMessage: "Swietnie! Udalo ci sie odnalezc wymagana liczbe miejsc. Mozesz teraz odnalezc skrytke finalowa.",
        finalContent: "Geocache jest ukryty tutaj:\n%\n",
        hint: "Hint",
        spoiler: "Spoiler",
        welcome: "Witaj %!",
        worthPoints: "Ta strefa byla warta % punktow.",
        completionCodeTitle: "Kod Wherigo",
        completionCodeContent: "Kod weryfikacyjny wherigo:",
    },
};
